serverdata = [
	{
		className:'server_cont1',
		imgb:'images/diannao.png',
		imgw:'images/diannao1.png',
		title:'企业官网',
		info:'打造高端网站与客户游览体验相结合的网站。',
		maskpic:'images/serv1.png'
	},
	{
		className:'server_cont1',
		imgb:'images/weixin.png',
		imgw:'images/weixin1.png',
		title:'营销型网站',
		info:'数十项搜索引擎优化指标，让网站变成营销利器。',
		maskpic:'images/serv2.png'
	},
	{
		className:'server_cont2',
		imgb:'images/pingban.png',
		imgw:'images/pingban1.png',
		title:'手机网站',
		info:'抢占移动互联网，领先竞争对手。',
		maskpic:'images/serv3.png'
	},
	{
		className:'server_cont3',
		imgb:'images/dp.png',
		imgw:'images/dp1.png',
		title:'H5/响应式',
		info:'一站适配PC/IPAD/手机，引领潮流。',
		maskpic:'images/serv4.png'
	},
	{
		className:'server_cont3',
		imgb:'images/vip.png',
		imgw:'images/vip1.png',
		title:'VI设计',
		info:'LOGO/VI/画册/海报设计，为您的品牌不懈努力。',
		maskpic:'images/serv5.png'
	},
]
casedata = [
  {
    img:'images/case01.jpg',
    title:'印象视界西藏旅游',
    info:'上市公司、官方网站、欧美风格'
  },
  {
    img:'images/case02.jpg',
    title:'TRT International国际货运',
    info:'上市公司、官方网站、欧美风格'
  },
  {
    img:'images/case03.jpg',
    title:'2016全国儿童艺术大赛官网设计',
    info:'上市公司、官方网站、欧美风格'
  },
]
teamdata = [
	{
		img:'images/lc1.png',
		imghover:'images/lc.png',
		job:'创意指导-李晨'
	},
	{
		img:'images/zzz1.png',
		imghover:'images/zzz.png',
		job:'技术经理-张真真'
	},
	{
		img:'images/whq1.png',
		imghover:'images/whq.png',
		job:'网页设计师-王怀庆'
	},
	{
		img:'images/lqk1.png',
		imghover:'images/lqk.png',
		job:'客户经理-吕启凯'
	},
	{
		img:'images/myl1.png',
		imghover:'images/myl.png',
		job:'客户经理-孟月雷'
	},
	{
		img:'images/lw1.png',
		imghover:'images/lw.png',
		job:'技术支持-李旺'
	},
	{
		img:'images/yjl1.png',
		imghover:'images/yjl.png',
		job:'研发工程师-杨建龙'
	},
	{
		img:'images/zwn1.png',
		imghover:'images/zwn.png',
		job:'客户经理-郑伟娜'
	},
	{
		img:'images/jl1.png',
		imghover:'images/jl.png',
		job:'客户经理-江林'
	}
]
newsdata = [
  {
    img:'images/case1.jpg',
    width:'504',
    height:'316',
    alt:'2016年国外主流导航栏设计趋势',
    date:'28',
    month:'July',
    info:'2016年国外主流导航栏设计趋势'
  },
  {
    img:'images/case2.jpg',
    width:'252',
    height:'158',
    alt:'助力巴铁宣传—锋云科技成功为华赢凯来提供网站改版服务！',
    date:'28',
    month:'July',
    info:'助力巴铁宣传—锋云科技成功为华赢凯来提供网站改版服务！'
  },
  {
    img:'images/case3.jpg',
    width:'252',
    height:'158',
    alt:'网站上线多久后才会被百度搜到？？？',
    date:'27',
    month:'July',
    info:'网站上线多久后才会被百度搜到？？？'
  },
  {
    img:'images/case4.jpg',
    width:'252',
    height:'158',
    alt:'手机版网站的重要性 不可小觑的手机群',
    date:'26',
    month:'July',
    info:'手机版网站的重要性 不可小觑的手机群'
  },
  {
    img:'images/case5.jpg',
    width:'252',
    height:'158',
    alt:'网站改版导致百度收录下降，该怎么办？',
    date:'30',
    month:'July',
    info:'网站改版导致百度收录下降，该怎么办？'
  }
]
custdata = [
  'images/logo.jpg','images/logo2.jpg','images/logo3.jpg','images/logo4.jpg','images/logo5.jpg','images/logo6.jpg','images/logo7.jpg','images/logo8.jpg','images/logo9.jpg','images/logo10.jpg','images/logo11.jpg','images/logo12.jpg','images/logo13.jpg','images/logo14.jpg','images/logo15.jpg','images/logo16.jpg','images/logo17.jpg','images/logo18.jpg','images/logo19.jpg','images/logo20.jpg'
]
